### PR TITLE
Code of Conduct

### LINKED ISSUE #8: Add Code of Conduct file
We should have a Code of Conduct!

### PR DESCRIPTION
**Pull request by bourque**
This PR adds a code of conduct document to the repository.  Closes #8.

### CODE REVIEW

**Comment by bourque** [comment]
Hey @nespinoza and @rcooper295.  Could you all review this whenever you have a chance and let me know if we are missing anything important here, or if anything should be modified?  Thank you!

One area that I am unsure of is under "enforcement" section, where it says that violations can be brought up with any of the `exo-bespin` team members.  I just put that there for now, but this could be a problem if one of us (or any future developers on the team) violates this CoC, in which case it may be best to bring up the issue to someone outside of the team.  Since this is a JDF project and we are not reporting to any specific branch or division, I'm not sure what the appropriate avenue for this is. 🤔 Perhaps just HR in general?

**Comment by bourque** [comment]
@nespinoza @rcooper295 Could I get your blessing (or suggestions for improvement) on this?

**Review by rcooper295 — APPROVED** [review]
This looks great to me. Very thorough. I understand your uncertainty about the best way to enforce this code of conduct in the situation where one of us is the one violating it. Of course we can go to HR, but that doesn't really apply if it's someone from outside the institute who wants to submit a complaint about one of us. I think it's fine the way it is, since if one of the team members is harassing someone, presumably there are still other team members they could contact to report a violation of the code of conduct.

**Review by nespinoza — COMMENTED** [review]
I really like this code of conduct --- and agree with @rcooper295's comments. Thanks for writing this!

**Review by nespinoza — APPROVED** [review]

**Pull request merged**
